services:
  redis:
    image: redis:7
    container_name: golladrim-redis
    ports:
      - "6379:6379"
    volumes:
      - golladrim-redis-data:/data
    restart: unless-stopped

volumes:
  golladrim-redis-data:
